#!/bin/bash

# A simple script to create the environment for RADSA.
# In order for the configuration in this script to apply to the outer
# environment, this script will need to be called as `. activateEnv`
# instead of ./activateEnv .

# The DATABASE_URL should be configured as it is in the example below.
# DATABASE_URL='postgres://{role_name}:{password}@{host}/{database_name}'

export DATABASE_URL='postgres:///ra_sched'

# The next two are for developing purposes only
# They allow oauth2 to be used over http instead of https
export OAUTHLIB_RELAX_TOKEN_SCOPE=1
export OAUTHLIB_INSECURE_TRANSPORT=1

# The following need to be set with the appropriate oAuth2 information.
export SECRET_KEY=
export CLIENT_ID=
export CLIENT_SECRET=
